### ISSUE TITLE
Default code raised Loaderror

### ISSUE THREAD

**Issue by byojelly** [learn-co-curriculum/writing-migrations#12]
After copying the repo locally, the default code from the lab created a load error when trying to use "rake -T" or "rake db:migrate"

my operating system - ubuntu (linux)

when running rake -T i received the following
// ♥ rake -T
rake aborted!
LoadError: cannot load such file -- sinatra/activerecord/rake
/home/alex/code/labs/writing-migrations-v-000/Rakefile:5:in `require'
/home/alex/code/labs/writing-migrations-v-000/Rakefile:5:in `<top (required)>'
/home/alex/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/alex/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

I opened a question for the lab.  The instructor was able to fix the problem by removing the following code from the default Rakefile:
        #require 'sinatra/activerecord/rake'
When the above code was commented out, rake worked properly.

This issue originated from the labs default code. Not sure if changes are required for lab.

**Comment by mikeries** [comment]
I have a student seeing this also, but the Rakefile doesn't have the `require` referenced above.

If I clone the lab to my local machine, run bundle, then `rake db:create` I receive the following:

rake aborted!
NameError: uninitialized constant ActiveRecord::Tasks::DatabaseTasks::Rails
/home/michael/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:75:in `env'
/home/michael/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:105:in `create_current'
/home/michael/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/home/michael/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/michael/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We updated the dependencies for this lesson and using ruby version 2.3.3 we are no longer seeing the error message above.

As always thank you for contributing!
