### ISSUE TITLE
missing info 

### ISSUE THREAD

**Issue by gbs4ever** [learn-co-curriculum/writing-migrations#15]
The **read me** is missing the names of the  2&3 class for the migration db/migrate  dir       (yes you can  get it from the error ) but it should be in the read me. What the name of the class is? that could be anything in the world as it is up to each dev to name it how he wants.

**Comment by maxwellbenton** [comment]
Hi @gbs4ever,

Thank you for opening this issue and providing feedback. We've updated this lesson's readme to include the class names that are expected by the tests, and believe this issue is resolved.

Thank you for contributing to a Learn lesson!
