### ISSUE TITLE
Spec Helper bad relative - mixed lab goals

### ISSUE THREAD

**Issue by jakebrady5** [learn-co-curriculum/writing-migrations#2]
Spec helper requires a relative that does not exist.  Lab has students writing migrations, but tests are trying to test with a Student class that does not exist (the one required by spec helper).

Migrations are also already written in completely already, ie solution is given immediately.

**Comment by victhevenot** [comment]
Hey @jakebrady5,

Thanks so much for opening an issue! I took a look, and it seems like all of these issues has been resolved. I'm going to go ahead and close this issue, but please let me know if you think its still a problem!
