### ISSUE TITLE
Already existing files cause migration issues + rake tasks

### ISSUE THREAD

**Issue by samnags** [learn-co-curriculum/writing-migrations#8]
@AnnJohn @pletcher 
The lab has the student run the migrations, then write three migration files, then re-run. Problem is the lab clones with all three files, so students edit them and run the migrations, but they don't update since migrations were already run. Student workaround is either delete files and recreate or rake:db:reset (if we tell them about it). I'd suggest removing the migration files. 

Also the rake tasks is missing rake:db:create.

If you're okay with suggestions, I'm happy to make them myself if you want to tag me.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to ASAP.

**Comment by pletcher** [comment]
@samnags good catch. Let's add the migration files to the .gitignore, at least on `master`
